# Generated by Django 4.0.3 on 2022-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulzioon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulzion',
            name='Option1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pulzion',
            name='Option2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pulzion',
            name='Option3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pulzion',
            name='Option4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pulzion',
            name='Optionans',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pulzion',
            name='Question',
            field=models.CharField(max_length=100),
        ),
    ]
